### ISSUE TITLE
Bot posts links to MLTSHP repost instead of original post

### ISSUE THREAD

**Issue by tmpkco** [MLTSHP/best-of-mltshp-bot#10]
When the bot posts an image, it’s not posting a link to the original account that has all the likes. It’s posting a link to MLTSHP account instead of a link to the original post that has gotten all the likes. The latter behavior is the way the twitter bot operated

Example: this is the link the bot posts: https://mltshp.com/p/1Q5J1 (1 like)
But that is a saved to shake repost of this: https://mltshp.com/p/1Q5I8 (edited) 

The reposted image often has few to zero likes, making it look unpopular. It also erases the comments and context that sometimes helps explain the post.

**Comment by bradchoate** [comment]
Since the bot consumes the https://mltshp.com/user/mltshp/rss feed, it is using the link provided there, which is the repost. To address this, we have some choices:

1. The bot could be updated to fetch the repost page link and gather the original post link (always included in an element found using the selector `.content .originally-posted-by .the-post`).
2. MLTSHP's RSS feed could be updated to include an `atom:link` element with a "via" rel attribute to link to originating post. This would also require changes to the bot to consume this new element. This would be applied to all RSS feeds.
3. MLTSHP could alter the feed output for the "Popular" RSS feed specifically, so that it directly links to the originating post instead of the repost.

**Comment by dphiffer** [comment]
Please see: https://github.com/MLTSHP/mltshp/pull/760

And related issue: https://github.com/MLTSHP/mltshp/issues/754

**Comment by bradchoate** [comment]
Verified fixed (via implementing option 3).
